myproject/app1/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.customer_list, name='customer_list'),
    url(r'^app/$', views.customer_add, name='customer_add'),
    url(r'^edit/(?P<customer_id>[0-9]+)/$', views.customer_edit, name='customer_edit'),
    url(r'^delete/(?P<customer_id>[0-9]+)/$', views.customer_delete, name='customer_delete'),
]

myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app1.urls', namespace='app')),
]

myproject/app1/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Customer(models.Model):
	name = models.CharField(max_length=75, verbose_name='Nombre')
	age = models.IntegerField(default=0, verbose_name='Edad')
	phone = models.CharField(max_length=10, verbose_name='Telefono')
	status = models.BooleanField(default=True)

	class Meta:
		db_table='customers'
		#ordering = ['age']

myproject/app1/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import Customer

class CustomerForm(forms.ModelForm):
	name = forms.CharField(
		label = 'Nombre',
		min_length = 3,
		widget = forms.TextInput(
			attrs = {
			}
		)
	)

	age = forms.IntegerField(
		label = 'Edad',
		widget = forms.NumberInput(
			attrs = {
				'required':'required',
				'class':'myclass',
			}
		)
	)

	phone = forms.CharField(
		label = 'Telefono',
		widget = forms.NumberInput(
			attrs = {
			}
		)
	)

	class Meta:
		model = Customer
		fields = ('name', 'age', 'phone',)

myproject/app1/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, Http404

from .forms import CustomerForm
from .models import Customer

# Create your views here.
def customer_list(request):
	customers = Customer.objects.filter(status=True)
	return render(request, 'app1/customer_list.html', {'customers':customers})

def customer_add(request):

	cust_form = CustomerForm()

	cust_form = CustomerForm(request.POST or None)

	if cust_form.is_valid():

		cust_form.save()

		return redirect('app:customer_list')

	return render(request, 'app1/customer_form.html', {'form':cust_form})

def customer_edit(request, customer_id):
	customer = Customer.objects.get(pk=customer_id)

	cust_form = CustomerForm(request.POST or None, instance=customer)

	if cust_form.is_valid():

		cust_form.save()

		return redirect('app:customer_list')

	return render(request, 'app1/customer_form.html', {'form':cust_form})

def customer_delete(request, customer_id):
	
	try:
		customer = Customer.objects.get(pk=customer_id)
		customer.status = False
		customer.save()
	except Exception as e:
		raise Http404

	return redirect('app:customer_list')

myproject/app1/templates/app1/customer_form.html
<!DOCTYPE html>
<html>
<head>
	<title>Clientes</title>
</head>
<body>
	<h1>Formulario de clientes</h1>
	<form method="POST" action="">
		{% csrf_token %}
		<p>{{form.name.label}} : {{form.name}}</p>
		<p>{{form.age.label}} : {{form.age}}</p>
		<p>{{form.phone.label}} : {{form.phone}}</p>
		<p> <a href="{% url 'app:customer_list' %}">Cancelar</a> - <button type="submit">Guardar</button></p>
	</form>
</body>
</html>

myproject/app1/templates/app1/customer_list.html
<!DOCTYPE html>
<html>
<head>
	<title>Clientes</title>
</head>
<body>
	<h1>Clientes</h1>
	<a href="{% url 'app:customer_add' %}">Agregar Cliente</a>
	{% for customer in customers %}
		<p>{{customer.id}}
		<a href="{% url 'app:customer_edit' customer.id %}">{{customer.name}}</a>
		{{customer.age}}
		<a href="{% url 'app:customer_delete' customer.id%}"> Borrar</a>
		</p>
	{% endfor %}
</body>
</html>

myproject/app1/templates/app1/template1.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>{{message}}</h1>
</body>
</html>